# Generated by Django 5.0.1 on 2024-02-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_add_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='age',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
    ]
