# Generated by Django 5.0.1 on 2024-02-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
