# Generated by Django 5.0.1 on 2024-02-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0006_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.add_services'),
        ),
    ]
