# Generated by Django 5.0.1 on 2024-02-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0010_services_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=22, null=True)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.services')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.registration')),
            ],
        ),
    ]
