# Generated by Django 5.0.1 on 2024-02-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0011_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.servicerregistration'),
        ),
    ]
