# Generated by Django 5.0.1 on 2024-03-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0012_requests_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
