# Generated by Django 4.2.4 on 2024-03-18 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0015_services_servicer_alter_services_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(max_length=22, null=True)),
                ('comment', models.CharField(max_length=22, null=True)),
                ('status', models.CharField(max_length=22, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.registration')),
                ('workers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.services')),
            ],
        ),
    ]
