# Generated by Django 4.2.4 on 2024-03-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0017_alter_rating_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.servicerregistration'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
