# Generated by Django 4.2.4 on 2024-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0019_assign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='workstatus',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
