# Generated by Django 4.2.4 on 2024-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0020_assign_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
