# Generated by Django 4.2.4 on 2024-04-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0022_requests_bookingdate_requests_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='paymentstatus',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
