# Generated by Django 4.2.4 on 2024-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0023_assign_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='amount',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
